### ISSUE TITLE
Website needs better buttons

### ISSUE THREAD

**Issue by cadop** [cadop/dhart#18]
The current index.html simply defines some HTML buttons to navigate to individual docs.  It would be nice to improve this landing/splash page.

**Comment by lodenrogue** [comment]
Do you have some idea of how you would like them to look? Or a reference page for insipiration?

**Comment by cadop** [comment]
@lodenrogue  Were you willing to help on this, or any other info you were looking for from me?

**Comment by lodenrogue** [comment]
No, I just wanted to clarify what you were looking for in case someone wanted to help.
