### ISSUE TITLE
Overloads for C# interface to accept floats

### ISSUE THREAD

**Issue by cadop** [cadop/dhart#47]
port optimizations from `OcclusionRays` to other methods such as this one ?
https://github.com/cadop/dhart/blob/26102d0f38860b8855df3670de68053aa372ae71/src/Csharp/packages/raytracer/src/RayTracerNative.cs#L249-L254

_Originally posted by @mariuszhermansdorfer in https://github.com/cadop/dhart/issues/46#issuecomment-1382430379_

**Comment by mariuszhermansdorfer** [comment]
@cadop, 
I added overloads to the remaining methods to accept `float[]` as input as well. Would you like me to push these to the dev branch as well?
![image](https://user-images.githubusercontent.com/49192999/213813063-dd5e3607-452c-4051-b467-407c02c1ede5.png)

**Comment by cadop** [comment]
@mariuszhermansdorfer yes that would be great thank you!

**Comment by cadop** [comment]
Also I just realized what your comment was.  I thought it was talking about OpenMP, which is what I did on the dev branch recently.  Now I see what you asked!

**Comment by mariuszhermansdorfer** [comment]
Your initial interpretation was right - I asked to port all optimizations to other methods as well. Both the `float[]` input and `OpenMP`

**Comment by mariuszhermansdorfer** [comment]
Could you point me to where the OpenMP are optimizations are in the previous code so that I could try and scale it to the other methods?

**Comment by cadop** [comment]
I already did the update to openmp on dev
